### PR TITLE
 WamProcessor: Order event scheduling by time

### PR DESCRIPTION
**Pull request by boourns**
Currently if I call `scheduleEvents` with times like `A: now, B: now+200ms, C: now`, what will happen is

event A emitted now
event B emitted 200ms later
event C emitted after B -- 200ms late!

The fix here, is.. on scheduleEvents, sort the events by event time so that regardless of the schedule event order, we emit them at the desired times.

In practice I schedule MIDI_OFF messages into the future in the same context as when I schedule MIDI_ON messages, which means the client code does not have to remember what MIDI notes are still on and need an OFF to be sent.

### CODE REVIEW

**Comment by boourns** [comment]
I put this on top of my other PR that's open just so that I can reference this commit for my builds, but ideally both PRs get merged :)

**Comment by owengc** [comment]
> In practice I schedule MIDI_OFF messages into the future in the same context as when I schedule MIDI_ON messages, which means the client code does not have to remember what MIDI notes are still on and need an OFF to be sent.

i'd be wary of handling scheduling like this, as bugs can occur when user updates the midi notes on the fly in the DAW if you're not careful to cancel previously scheduled events, but that's a host problem.

thanks for catching this, my scheduling code assumes sorted by time but i was expecting the host to handle it. this is safer

events can also be scheduled from [main thread](https://github.com/webaudiomodules/sdk/blob/6fe5454dc484cbb7454ef7fe472b4ba452891d7c/src/WamProcessor.js#L265) though, so the bug isn't totally fixed yet.

so i think the best thing would probably be to add a flag like `_newEventsAdded` and check for this [here](https://github.com/webaudiomodules/sdk/blob/6fe5454dc484cbb7454ef7fe472b4ba452891d7c/src/WamProcessor.js#L474). so it would be like

```
...
                         /** @type {boolean} */
			this._destroyed = false;
                         /** @type {boolean} */
			this._newEventsAdded = false;
...


...
else if (verb === 'add') {
					if (noun === 'event') {
						const { event } = content;
						this._eventQueue.push({ id, event });
                                                  this._newEventsAdded = true;
						return; // defer postMessage until event is processed
					}
...					


...
scheduleEvents(...events) {
			let i = 0;
			while (i < events.length) {
				// no need for ids if scheduled from audio thread
				this._eventQueue.push({ id: 0, event: events[i] });
				i++;
			}
			
			this._newEventsAdded = true;
		}
...

...
_getProcessingSlices() {
			const response = 'add/event';
			/** @ts-ignore */
			const { currentTime, sampleRate } = audioWorkletGlobalScope;
			/** @type {{[sampleIndex: number]: WamEvent[]}} */
			const eventsBySampleIndex = {};
			// events must sorted by time
                         if (this._newEventsAdded) {
                             this._eventQueue.sort((a, b) => a.event.time - b.event.time);
                             this._newEventsAdded = false;
                         }
                         let i = 0;
			while (i < this._eventQueue.length) {
                         ...
```

(sorry for the weird code formatting..the indentation didn't all copy properly)

**Comment by boourns** [comment]
@owengc thanks for catching that! updated the code, also skipping the sort when there's only 1 element in the event queue (which is most of the time)

**Comment by owengc** [comment]
awesome, looks good to me! thanks for updating it

**Review by Fr0stbyteR — APPROVED** [review]

**Comment by micbuffa** [comment]
ok for me.

**Pull request merged**
